// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skafzkzjaszxgqryzhjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrYWZ6a3pqYXN6eGdxcnl6aGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTM3NzMsImV4cCI6MjA2MDgyOTc3M30.skHtn0jpXE5y7Js6yl_Y0Yi-mBYZnv216RdXJIa-jbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});